"""tablas iniciales superadmin

Revision ID: a47ac3568278
Revises: 
Create Date: 2026-09-10 23:54:54.185689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47ac3568278'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('precio_mensual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_proyectos', sa.Integer(), nullable=True),
    sa.Column('max_usuarios', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('dominio', sa.String(length=200), nullable=False),
    sa.Column('color_primario', sa.String(length=10), nullable=True),
    sa.Column('color_secundario', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('id_plan', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('provisionando', 'activo', 'suspendido', 'cancelado', 'error', name='estado_tenant_enum'), nullable=False),
    sa.Column('coolify_app_uuid', sa.String(length=100), nullable=True),
    sa.Column('coolify_db_uuid', sa.String(length=100), nullable=True),
    sa.Column('db_host', sa.String(length=200), nullable=True),
    sa.Column('db_nombre', sa.String(length=100), nullable=True),
    sa.Column('db_usuario', sa.String(length=100), nullable=True),
    sa.Column('db_password', sa.String(length=200), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_plan'], ['planes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dominio'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('historial_provisionamiento',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_tenant', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_tenant'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_provisionamiento')
    op.drop_table('tenants')
    op.drop_table('planes')
    op.drop_table('admin_usuarios')
    # ### end Alembic commands ###